#Atividade de Frequência



*   Entregar um algoritmo de multiplicação de matrizes implementado em Python

## 1.   *Importações dos módulos gerais*

    * Aqui será importado o numpy. Ele será utilizado tanto para criação como multiplicação de matrizes.




In [1]:
import numpy as np

## 2.  Criação e multiplicação de matrizes


    * Criação de Matrizes

In [4]:
#Será criado uma matriz 3x3. Os valores da mesma serão aleatórios para cada execução do código porêm os valores 
#serão variados para cada execução da célula.
Matriz_1 = np.random.random((3, 3))
Matriz_1

array([[0.77047221, 0.82924202, 0.62766818],
       [0.74876418, 0.54256861, 0.4982957 ],
       [0.34421273, 0.37407983, 0.17123331]])

In [5]:
#A matriz 2 será criada com o mesmo método da Matriz_1.
Matriz_2 = np.random.random((3, 3))
Matriz_2

array([[0.81547752, 0.28088655, 0.22752298],
       [0.11212921, 0.65656157, 0.28162533],
       [0.22535263, 0.59271183, 0.64632241]])

    * Multiplicação de Matrizes

In [6]:
Mult_M = np.dot(Matriz_1, Matriz_2)
Mult_M

array([[0.8627317 , 1.13289008, 0.8145117 ],
       [0.7837304 , 0.86189325, 0.6452218 ],
       [0.3612309 , 0.44378318, 0.29433859]])